version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: orgguard_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@1234
      POSTGRES_DB: orgguard
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: