version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: orgguard_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@1234
      POSTGRES_DB: orgguard
    ports:
      - "5432:5432"
